global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gopherex-services"
    static_configs:
      - targets: [ "host.docker.internal:9091" ]
        labels:
          service: "funds-service"

